config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: "index#index"
  get '/signup', to: "sessions#new_signup"
  post '/signup', to: "sessions#create_for_new_user"
  get '/login', to: "sessions#new_login"
  post '/login', to: "sessions#create_for_existing_user"
  delete '/logout', to: "sessions#destroy"

  resources :u, controller: "users", only: [:show], param: :username

  resources :chatrooms, param: :slug
  resources :messages

  root 'index#index'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
  before_validation :sanitize, :slugify


  def to_param
    self.slug
  end

  def slugify
    self.slug = self.topic.downcase.gsub(" ", "-")
  end

  def sanitize
    self.topic = self.topic.strip
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class UsernameValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /^[A-Za-z0-9-_]{3,50}$/
      record.errors[attribute] << (options[:message] || "is not a valid username. (Can only contain letters, numbers, dashes - and underscores _)")
    end
  end
end


class User < ApplicationRecord
  has_many :messages
  has_many :chatrooms, through: :messages

  validates :username, presence: true, length: { maximum: 50, minimum: 3 }, uniqueness: { case_sensitive: false }, username: true
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }

  has_secure_password

  before_save do
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :check_if_logged_in

  def index
    @chatroom = Chatroom.new
    @chatrooms = Chatroom.all.order('topic asc')
  end

  def new
    @chatroom = Chatroom.new
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    if @chatroom.save
      respond_to do |format|
        format.html { redirect_to @chatroom }
        format.js
      end
    else
      respond_to do |format|
        flash[:notice] = {error: ["a chatroom with this topic already exists"]}
        format.html { redirect_to new_chatroom_path }
        format.js { render template: 'chatrooms/chatroom_error.js.erb'} 
      end
    end
  end

  def show
    @chatroom = Chatroom.find_by(slug: params[:slug])
    @message = Message.new
  end

  private

    def chatroom_params
      params.require(:chatroom).permit(:topic)
    end

    def check_if_logged_in
      if !logged_in?
        redirect_to root_path
        flash[:notice] = "Please login before going to a chatroom."
      end
    end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    message = Message.new(message_params)
    message.user = current_user
    if message.save
      ActionCable.server.broadcast 'messages',
        message: message.content,
        user: message.user.username
      head :ok
    end
  end

  private

    def message_params
      params.require(:message).permit(:content, :chatroom_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new_signup
  end

  def new_login
  end

  def create_for_existing_user
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      # Handle the logic for after a user is authenticated
      helpers.log_in(user)
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email or password.'
      render 'new_login'
    end
  end

  def create_for_new_user
    @user = User.create(username: params[:session][:username], email: params[:session][:email], password: params[:session][:password])

    if @user.errors.count < 1
      helpers.log_in(@user)
      flash[:success] = "New account created!"
      redirect_to root_url
    else
      render 'new_signup'
    end

    # if user
    #   user.save
    #   flash.now[:success] = 'Account created!'
    #   redirect_to root_url
    # end
  end

  def destroy
    helpers.log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_username(params[:username])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatrooms/_chatroom.html.erb
<li><%= link_to chatroom.topic, chatroom_path(chatroom) %></li>

app/views/chatrooms/_chatroom_form.html.erb
<div class="chatroom-form">
  <%= form_for chatroom, remote: true do |f| %>
    <div class="input-group">
      <span class="input-group-addon">topic:</span>
      <%= f.text_field :topic, class: "form-control"%>
    </div>
    <%= f.submit class: "btn btn-primary", id: "create-chatroom" %>
  <% end %>
</div>

app/views/chatrooms/index.html.erb
<div class="row col-md-8 col-md-offset-2" id="chatroom-title">
  <h1>Chatrooms</h1>
</div>

<div class="row col-md-8 col-md-offset-2" id="chatrooms">

  <% if @chatrooms.any? %>
    <ul>
      <%= render @chatrooms%>
    </ul>
  <%else %>
    <p>Looks like there is nothing here.</p>
  <% end %>

</div>

app/views/chatrooms/new.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1>Create a new chatroom</h1>
</div>

<div class="row col-md-8 col-md-offset-2">
    
  <div class="chatroom-form">
      <%= form_for @chatroom do |f| %>

        <div class="form-group">
          <%= f.label :topic %>
          <%= f.text_field :topic, class: "form-control"%>
        </div>

        <div class="form-group">
          <%= f.submit class: "btn btn-primary", id: "create-chatroom" %>
        </div>

      <% end %>
      
  </div>

</div>

app/views/chatrooms/show.html.erb
<div class="row col-md-8">
  <h1><%= @chatroom.topic %></h1>
</div>

<div class="row col-md-8">
  <div class="panel panel-default">
    <% if @chatroom.messages.any? %>
      <div class="panel-body" id="messages">
        <span class="nothing-to-see-here">Nothing more above here!</span>
        <%= render partial: 'messages/message', collection: @chatroom.messages%>
      </div>
    <%else%>
      <div class="panel-body hidden" id="messages">
      </div>
    <%end%>
  </div>

</div>

<div class="row col-md-6">
  <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom}%>
</div>

app/views/index/index.html.erb
<div class="row col-md-8 col-md-offset-2">

  <h1>Simple Text Chat</h1>

  <p>Sign in, create or join a chatroom, and start chatting to others!</p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Text Chat</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    
    <nav class="navbar navbar-dark navbar-expand-lg bg-dark navbar-toggleable-md">
      <a class="navbar-brand" href="/">Simple Text Chat</a>

      <div class="navbar-nav mr-auto">
      
      <%= link_to "All Chatrooms", chatrooms_path, class: "nav-item nav-link"  %>
      <%= link_to "New Chatroom", new_chatroom_path, class: "nav-item nav-link"  %>

      </div>

      <div class="navbar-nav mr-right">
        <% if logged_in? %>
          <span class="navbar-text">
            Logged in as: <span class="username"><%= link_to current_user.username, u_path(current_user.username) %></span>
          </span>
          <%= link_to "Logout", logout_path, method: :delete, class: "nav-item nav-link"  %>
        <% else %>
          <%= link_to "Login", login_path, class: "nav-item nav-link"  %>
          <%= link_to "Signup", signup_path, class: "nav-item nav-link"  %>
        <% end %>

      </div>
      
    
    </nav>

  </header>

  <body>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<p><strong><%=link_to message.user.username, u_path(message.user.username)%>:</strong> <%=message.content%></p>

app/views/messages/_message_form.html.erb
<%= form_for message, remote: true, authenticity_token: true do |f| %>
  <%= f.label :your_message %>
  <%= f.text_area :content, class: "form-control", data: {textarea: "message"} %>

  <%= f.hidden_field :chatroom_id, value: chatroom.id %>
  <%= f.submit "Send", class: "btn btn-primary", style: "display: block", data: {send: "message"} %>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<% if current_user.present? && current_user.id == @user.id %>
  <p>Hey, thats you!</p>
<% end %>

<p>
  <strong>Joined:</strong>
  <%= @user.created_at %>
</p>